# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#                
#        
#                
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Set new version inscrease by 1 And build project
      run: |
        cd my-app
        ls -l
        mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit
        mvn -B package
        java -cp target/classes com.mycompany.app.App
        mkdir artifact-app && cp target/*.jar artifact-app
        ls -l
        
    - name: Publish to Artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-actions-artifact
        path: my-app/artifact-app
  
  
    - name: Download from Artifact
      uses: actions/download-artifact@v3
      with:
        name: github-actions-artifact
        path: target\
    - name: test
      run: |
       pwd
       ls
       cat target\
       
    - name: test2
      run: |
       pwd
       ls


      
      
    - name: Build a dockerfile
      run: |
        cd my-app
        docker build -t my-app-tomerangel:1.0.1-SNAPSHOT .
      
    - name: Push Image to DockerHub
      run: |
        docker login -u ${{ secrets.USER_NAME }} -p ${{ secrets.USER_PASS }}
        docker tag my-app-tomerangel:1.0.1-SNAPSHOT 102030102030/my-app-tomerangel:1.0.1
        docker push 102030102030/my-app-tomerangel:1.0.1
      
      
